version: "3.9"
services:
  # Application frontend cloud
  cloudfront:
    build:
      context: netology-diplom-frontend
      dockerfile: Dockerfile
    container_name: cloudfront
    image: cloudfront:latest
    ports:
      - "8081:8080"